### ISSUE TITLE
Wrapping properties into multiple lines

### ISSUE THREAD

**Issue by emoryy** [machty/emblem-site#15]
It's not included on emblemjs.com, so I've looked into the test specs, and I've found that it is possible to wrap properties into more lines with the use of brackets. I guess this should be mentioned in the Syntax docs.

Also it doesn't seem to work properly with Ember helpers, for example with `Ember.Select`
Static attributes are good (`class="something"`), however attribute bindings doesn't seem to work either in the form of `value=something` or `valueBinding="something"`.
This is what I tried:

```
Ember.Select [
  content=something
  optionValuePath="content.value"
  optionLabelPath="content.label"
  value=somethingValue
  class="something" ]
```

**Comment by talexand** [comment]
What happened to this? It still works with `= input` but not with, say, https://www.npmjs.com/package/ember-bootstrap-datetimepicker.
