### ISSUE TITLE
emblem.js and each as blocks

### ISSUE THREAD

**Issue by vkoves** [machty/emblem-site#31]
Howdy, I was having a problem converting some Handlebars syntax to Emblem. I've just starting using Emblem so I'm sure it's simple, but it was not shown how this could be done in Emblem on the site:

`{{#each model as |feeditem|}}
	<h4>{{feeditem.title}}</h4>
	<h5>{{feeditem.text}}</h5>
{{/each}}`

Is there something I'm missing? Neither the Handlebars nor the Emblem work if I do an each in, so I'm quite puzzled.

**Comment by thec0keman** [comment]
@vkoves I believe this should work:
```
= each model as |feeditem|
  h4 = feeditem.title
  h5 = feeditem.text
```

**Comment by vkoves** [comment]
Wow, that's very useful and worked immediately. Thanks.
Maybe that should be added to the syntax page somewhere.

Also I was wondering if it was possible to make a line of Emblem with statements? I have this handlebars line that I am trying to convert:

`<h5> at {{feeditem.title}} on {{feeditem.text}}</h5>`

However when I try to make this into Emblem, it just prints the statement as text. Here's an example of what I did in Emblem:

`h5 at = feeditem.title`

How would I properly do this?

**Comment by thec0keman** [comment]
There are some inline helpers so you can do
```
h5 at #{ feeditem.title } on #{ feeditem.text }
```
