### ISSUE TITLE
emblem.js plz help: inline markup

### ISSUE THREAD

**Issue by a1s** [machty/emblem-site#34]
This is a sample template fragment from [Ember.js tutorial](https://guides.emberjs.com/v2.14.0/tutorial/routes-and-templates/#toc_a-contact-route):

```html
  <div class="right tomster"></div>
  <h2>Contact Us</h2>
  <p>Super Rentals Representatives would love to help you<br>choose a destination or answer
    any questions you may have.</p>
  <p>
    Super Rentals HQ
    <address>
      1212 Test Address Avenue<br>
      Testington, OR 97233
    </address>
    <a href="tel:503.555.1212">+1 (503) 555-1212</a><br>
    <a href="mailto:superrentalsrep@emberjs.com">superrentalsrep@emberjs.com</a>
  </p>
```

How can I do those `<br>` and `<address>` with Emblem.js?

**Comment by thec0keman** [comment]
[Example](https://mammothhr.github.io/try-emblem/#/?result=h2%20Contact%20Us%0Ap%20Super%20Rentals%20Representatives%20would%20love%20to%20help%20you%3Cbr%3Echoose%20a%20destination%20or%20answer%20any%20questions%20you%20may%20have.%0Ap%0A%20%20%20%20%7CSuper%20Rentals%20HQ%0A%20%20%20%20address%0A%20%20%20%20%20%20%7C1212%20Test%20Address%20Avenue%0A%20%20%20%20%20%20br%0A%20%20%20%20%20%20%7CTestington%2C%20OR%2097233%0A%20%20%20%20a%20href%3D%22tel%3A503.555.1212%22%20%2B1%20(503)%20555-1212%0A%20%20%20%20br%0A%20%20%20%20a%20href%3D%22mailto%3Asuperrentalsrep%40emberjs.com%22%20superrentalsrep%40emberjs.com)

**Comment by a1s** [comment]
I'll make a copy here:

```
h2 Contact Us
p Super Rentals Representatives would love to help you <br>
  choose a destination or answer any questions you may have.
p
    |Super Rentals HQ
    address
      |1212 Test Address Avenue
      br
      |Testington, OR 97233
    a href="tel:503.555.1212" +1 (503) 555-1212
    br
    a href="mailto:superrentalsrep@emberjs.com" superrentalsrep@emberjs.com
```

That did it.  Thanks a lot!
